"""empty message

Revision ID: 2cfa71ef92ba
Revises: ea5fc327e3ec
Create Date: 2023-03-23 19:27:18.373225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfa71ef92ba'
down_revision = 'ea5fc327e3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('accident_on_record',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('accident_on_record',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
